#!/usr/bin/env python

__author__ = 'riot'

from os import environ

import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug", help="Show debug outout",
                        action="store_true")
    parser.add_argument("--io", help="Show io options", action="store_true")
    parser.add_argument("--gui", help="Activate GUI (EXPERIMENTAL!)",
                        action="store_true")
    parser.add_argument("--cam", help="Activate Camera",
                        action="store_true")
    parser.add_argument("--nosplash", help="Disable splash screen",
                        action="store_true")
    parser.add_argument("--midiout", help="Select MIDI output device id",
                        type=int, default=None)
    parser.add_argument("--midiin", help="Select MIDI input device id",
                        type=int, default=None)
    parser.add_argument("--width", help="Output renderer width",
                        type=int, default=1920)
    parser.add_argument("--height", help="Output renderer height",
                        type=int, default=1200)
    parser.add_argument("--host", help="Output matelight host(name)",
                        type=str, default="matelight")
    parser.add_argument("--port", help="Output matelight port",
                        type=int, default=1337)
    parser.add_argument("--program",
                        help="Load named router program from "
                             "~/.avio/router_*.json",
                        type=str,
                        default='default')


    args = parser.parse_args()

    if not args.gui:
        environ['SDL_VIDEODRIVER'] = 'dummy'
        print("Headless mode. To exit, hit CTRL-C.")

    from avio_core.app import Launch

    Launch(args)
